# Generated by Django 5.2.6 on 2026-04-23 09:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='+62', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_mid_name',
            field=models.CharField(default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Aero', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('staf', 'Staf')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='salutation',
            field=models.CharField(default='Mr', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='tanggal_lahir',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
