# Generated by Django 5.2.6 on 2026-04-30 03:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_country_code_alter_user_first_mid_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id_penyedia', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('maskapai', 'Maskapai'), ('mitra', 'Mitra')], max_length=20)),
            ],
            options={
                'ordering': ['id_penyedia'],
            },
        ),
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email_mitra', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nama_mitra', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField(default=django.utils.timezone.localdate)),
                ('penyedia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mitra', to='core.penyedia')),
            ],
            options={
                'ordering': ['nama_mitra', 'email_mitra'],
            },
        ),
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('kode_hadiah', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('miles', models.PositiveIntegerField()),
                ('valid_start_date', models.DateField()),
                ('program_end', models.DateField()),
                ('penyedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadiah', to='core.penyedia')),
            ],
            options={
                'ordering': ['nama', 'kode_hadiah'],
            },
        ),
    ]
