# Generated by Codex on 2026-04-30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_award_miles_packages(apps, schema_editor):
    AwardMilesPackage = apps.get_model("core", "AwardMilesPackage")
    packages = [
        {
            "kode_package": "PKG001",
            "nama": "Starter Miles",
            "deskripsi": "Paket ringan untuk menambah saldo award miles.",
            "miles": 5000,
            "harga_idr": 250000,
        },
        {
            "kode_package": "PKG002",
            "nama": "Traveler Miles",
            "deskripsi": "Paket reguler untuk redeem hadiah dan perjalanan lebih fleksibel.",
            "miles": 12000,
            "harga_idr": 575000,
        },
        {
            "kode_package": "PKG003",
            "nama": "Explorer Miles",
            "deskripsi": "Paket besar dengan nilai terbaik untuk member aktif.",
            "miles": 25000,
            "harga_idr": 1100000,
        },
    ]
    for package in packages:
        AwardMilesPackage.objects.update_or_create(
            kode_package=package["kode_package"],
            defaults=package,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_penyedia_mitra_hadiah"),
        ("core", "0003_transfer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardMilesPackage",
            fields=[
                ("kode_package", models.CharField(max_length=20, primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True, default="")),
                ("miles", models.PositiveIntegerField()),
                ("harga_idr", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["miles", "kode_package"],
            },
        ),
        migrations.CreateModel(
            name="RedeemHadiah",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("miles_digunakan", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Diproses", "Diproses"),
                            ("Selesai", "Selesai"),
                            ("Dibatalkan", "Dibatalkan"),
                        ],
                        default="Diproses",
                        max_length=20,
                    ),
                ),
                ("catatan", models.CharField(blank=True, default="", max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hadiah",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redeem_hadiah",
                        to="core.hadiah",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeem_hadiah",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PembelianPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("harga_dibayar", models.PositiveIntegerField()),
                ("miles_diterima", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pembelian_package",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pembelian_package",
                        to="core.awardmilespackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RunPython(seed_award_miles_packages, migrations.RunPython.noop),
    ]
