# Generated by Django 5.2.4 on 2026-04-30 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_penyedia_mitra_hadiah'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('jumlah', models.IntegerField()),
                ('catatan', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameField(
            model_name='claimmissingmiles',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='bandara_asal',
            field=models.CharField(choices=[('CGK', 'CGK - Soekarno-Hatta, Jakarta'), ('DPS', 'DPS - Ngurah Rai, Bali'), ('SUB', 'SUB - Juanda, Surabaya'), ('KUL', 'KUL - Kuala Lumpur International'), ('SIN', 'SIN - Changi, Singapore'), ('NRT', 'NRT - Narita, Tokyo'), ('BKK', 'BKK - Suvarnabhumi, Bangkok'), ('HKG', 'HKG - Hong Kong International'), ('SYD', 'SYD - Kingsford Smith, Sydney'), ('MEL', 'MEL - Melbourne Airport'), ('AMS', 'AMS - Schiphol, Amsterdam'), ('LHR', 'LHR - Heathrow, London'), ('DXB', 'DXB - Dubai International'), ('DOH', 'DOH - Hamad, Doha'), ('ICN', 'ICN - Incheon, Seoul')], default='CGK', max_length=3),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='bandara_tujuan',
            field=models.CharField(choices=[('CGK', 'CGK - Soekarno-Hatta, Jakarta'), ('DPS', 'DPS - Ngurah Rai, Bali'), ('SUB', 'SUB - Juanda, Surabaya'), ('KUL', 'KUL - Kuala Lumpur International'), ('SIN', 'SIN - Changi, Singapore'), ('NRT', 'NRT - Narita, Tokyo'), ('BKK', 'BKK - Suvarnabhumi, Bangkok'), ('HKG', 'HKG - Hong Kong International'), ('SYD', 'SYD - Kingsford Smith, Sydney'), ('MEL', 'MEL - Melbourne Airport'), ('AMS', 'AMS - Schiphol, Amsterdam'), ('LHR', 'LHR - Heathrow, London'), ('DXB', 'DXB - Dubai International'), ('DOH', 'DOH - Hamad, Doha'), ('ICN', 'ICN - Incheon, Seoul')], default='DPS', max_length=3),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='flight_number',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='kelas_kabin',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], default='Economy', max_length=20),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='maskapai',
            field=models.CharField(choices=[('M1', 'M1 - Garuda Nusantara'), ('M2', 'M2 - Langit Air'), ('M3', 'M3 - Samudra Wings'), ('M4', 'M4 - Borneo Flight'), ('M5', 'M5 - Cakrawala Air')], default='M1', max_length=10),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='nomor_tiket',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='pnr',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='claimmissingmiles',
            name='tanggal_penerbangan',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddConstraint(
            model_name='claimmissingmiles',
            constraint=models.UniqueConstraint(fields=('email_member', 'flight_number', 'tanggal_penerbangan', 'nomor_tiket'), name='unique_claim_per_flight'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='email_member_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='email_member_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
