# Generated by Django 6.0.4 on 2026-04-30 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_transfer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identitas',
            fields=[
                ('nomor', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tanggal_habis', models.DateField()),
                ('tanggal_terbit', models.DateField()),
                ('negara_penerbit', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('Paspor', 'Paspor'), ('KTP', 'KTP'), ('SIM', 'SIM')], max_length=30)),
                ('email_member', models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='identitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal_terbit'],
                'unique_together': {('nomor',)},
            },
        ),
    ]
